version: '3'

services:
  web:
    build: ./app
    container_name: django_web.local.com
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      hello_django:
        ipv4_address: 172.10.0.3
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    container_name: django_postgres.local.com
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    ports:
      - "5432:5432"
    networks:
      hello_django:
        ipv4_address: 172.10.0.2

volumes:
  postgres_data:

networks:
  hello_django:
    driver: bridge
    ipam:
      config:
      - subnet: 172.10.0.0/16