version: '3'

services:
  web:
    build: ./app
    container_name: django_web.local.com
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      hello_django:
        ipv4_address: 172.10.0.3
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    container_name: django_postgres.local.com
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    ports:
      - "5432:5432"
    networks:
      hello_django:
        ipv4_address: 172.10.0.2

  elastic_search:
    image: blacktop/elasticsearch:7.8
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    container_name: django_elastic_search.local.com
    environment:
      - node.name=django_elastic_search.local.com
      - cluster.name=django_elastic_search.local.com
      - bootstrap.memory_lock=true
    ports:
      - "9200:9200"
    volumes:
        - elastic_search01_volume:/usr/share/elasticsearch/data
    networks:
      hello_django:
        ipv4_address: 172.10.0.4

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.8.0
    container_name: django_kibana.local.com
    volumes:
        - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "5601:5601"
    networks:
      hello_django:
        ipv4_address: 172.10.0.5
    depends_on:
      - elastic_search

  django-pgadmin:
    container_name: django_pgadmin.local.com
    image: dpage/pgadmin4
    restart: always
    links:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    depends_on:
      - db
    networks:
      hello_django:
        ipv4_address: 172.10.0.6

volumes:
  postgres_data:
  elastic_search01_volume:
  pgadmin:

networks:
  hello_django:
    driver: bridge
    ipam:
      config:
      - subnet: 172.10.0.0/16